# Generated by Django 5.1.4 on 2026-01-27 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Recruitment Consultancy Owner'), ('RECRUITER', 'Recruiter / HR Consultant'), ('CLIENT', 'Client Company'), ('CANDIDATE', 'Job Seeker'), ('ADMIN', 'System Administrator'), ('DEV_QA', 'Development & QA Team')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
