# Generated by Django 5.1.4 on 2026-01-30 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_job_created_at_job_experience_range_job_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidate')),
            ],
        ),
    ]
