# Generated by Django 5.1.4 on 2026-01-30 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recruiternote'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application'),
        ),
        migrations.AddField(
            model_name='interview',
            name='mode',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
