# Generated by Django 5.1.4 on 2026-01-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_interview_application_interview_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWED', 'Interviewed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='Applied', max_length=50),
        ),
    ]
