# Generated by Django 5.1.4 on 2026-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['user__username'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clientfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client Feedback', 'verbose_name_plural': 'Client Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-id'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['interview_date'], 'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobapproval',
            options={'verbose_name': 'Job Approval', 'verbose_name_plural': 'Job Approvals'},
        ),
        migrations.AlterModelOptions(
            name='recruiternote',
            options={'verbose_name': 'Recruiter Note', 'verbose_name_plural': 'Recruiter Notes'},
        ),
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'ordering': ['role'], 'verbose_name': 'Stakeholder', 'verbose_name_plural': 'Stakeholders'},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWED', 'Interviewed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='mode',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_range',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'candidate')},
        ),
    ]
