# Generated by Django 5.1.4 on 2026-02-13 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_interview_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application'),
        ),
    ]
