# Generated by Django 5.1.4 on 2026-02-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_job_experience_range_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_range',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
    ]
