# Generated by Django 4.2.28 on 2026-02-15 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_application_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('INTERVIEW', 'Interview'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClientPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jobs_posted', models.IntegerField(default=0)),
                ('total_applications_received', models.IntegerField(default=0)),
                ('total_hires', models.IntegerField(default=0)),
                ('average_time_to_hire', models.IntegerField(default=0)),
                ('new_hire_feedback_rating', models.FloatField(default=0)),
                ('new_hire_retention_days', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Performance',
                'verbose_name_plural': 'Client Performance',
            },
        ),
        migrations.CreateModel(
            name='PipelineMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('total_applications', models.IntegerField(default=0)),
                ('applied', models.IntegerField(default=0)),
                ('shortlisted', models.IntegerField(default=0)),
                ('interviewed', models.IntegerField(default=0)),
                ('offered', models.IntegerField(default=0)),
                ('hired', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('total_jobs_open', models.IntegerField(default=0)),
                ('total_jobs_filled', models.IntegerField(default=0)),
                ('total_jobs_closed', models.IntegerField(default=0)),
                ('application_to_interview_rate', models.FloatField(default=0)),
                ('interview_to_offer_rate', models.FloatField(default=0)),
                ('offer_to_hire_rate', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline Metrics',
                'verbose_name_plural': 'Pipeline Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed'), ('on_hold', 'On Hold')], db_index=True, default='open', max_length=20)),
                ('total_applications', models.IntegerField(default=0)),
                ('total_shortlisted', models.IntegerField(default=0)),
                ('total_interviewed', models.IntegerField(default=0)),
                ('total_offered', models.IntegerField(default=0)),
                ('hiring_date', models.DateTimeField(blank=True, null=True)),
                ('days_to_fill', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placement Tracker',
                'verbose_name_plural': 'Placement Trackers',
            },
        ),
        migrations.CreateModel(
            name='RecruiterPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jobs_posted', models.IntegerField(default=0)),
                ('total_applications_received', models.IntegerField(default=0)),
                ('total_hires', models.IntegerField(default=0)),
                ('average_time_to_hire', models.IntegerField(default=0)),
                ('average_cost_per_hire', models.FloatField(default=0)),
                ('offer_acceptance_rate', models.FloatField(default=0)),
                ('retention_rate_3_months', models.FloatField(default=0)),
                ('retention_rate_6_months', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recruiter Performance',
                'verbose_name_plural': 'Recruiter Performance',
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_active_users', models.IntegerField(default=0)),
                ('total_candidates', models.IntegerField(default=0)),
                ('total_clients', models.IntegerField(default=0)),
                ('daily_active_users', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('average_session_duration', models.IntegerField(default=0)),
                ('slow_requests_count', models.IntegerField(default=0)),
                ('failed_requests_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'System Metrics',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiternote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.candidate'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWED', 'Interviewed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], db_index=True, default='APPLIED', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main.candidate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='main.client'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapproval',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='recruiternote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_notes', to='main.candidate'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Recruitment Consultancy Owner'), ('RECRUITER', 'Recruiter / HR Consultant'), ('CLIENT', 'Client Company'), ('CANDIDATE', 'Job Seeker'), ('ADMIN', 'System Administrator'), ('DEV_QA', 'Development & QA Team')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-applied_at'], name='main_applic_status_4a7067_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate'], name='main_applic_candida_3ee746_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='main_applic_job_id_9b8579_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-created_at'], name='main_candid_created_b70535_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='main_client_company_1e48ff_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-created_at'], name='main_client_created_850ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='clientfeedback',
            index=models.Index(fields=['-created_at'], name='main_client_created_451856_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='main_feedba_created_9f87cb_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['interview_date'], name='main_interv_intervi_e0d32f_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['job', 'candidate'], name='main_interv_job_id_ab0120_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='main_job_title_822b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='main_job_locatio_56a9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', '-created_at'], name='main_job_is_acti_e80773_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['client', 'is_active'], name='main_job_client__2d4c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapproval',
            index=models.Index(fields=['is_approved'], name='main_jobapp_is_appr_078e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiternote',
            index=models.Index(fields=['candidate', '-created_at'], name='main_recrui_candida_02c6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholder',
            index=models.Index(fields=['role'], name='main_stakeh_role_8d0298_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['-timestamp'], name='main_system_timesta_7a9a0c_idx'),
        ),
        migrations.AddField(
            model_name='recruiterperformance',
            name='recruiter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementtracker',
            name='hired_candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.candidate'),
        ),
        migrations.AddField(
            model_name='placementtracker',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_tracker', to='main.job'),
        ),
        migrations.AddIndex(
            model_name='pipelinemetrics',
            index=models.Index(fields=['-date'], name='main_pipeli_date_34fb25_idx'),
        ),
        migrations.AddField(
            model_name='clientperformance',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='main.client'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recruiterperformance',
            index=models.Index(fields=['recruiter'], name='main_recrui_recruit_f0ebb6_idx'),
        ),
        migrations.AddIndex(
            model_name='placementtracker',
            index=models.Index(fields=['status', '-created_at'], name='main_placem_status_8d2880_idx'),
        ),
        migrations.AddIndex(
            model_name='placementtracker',
            index=models.Index(fields=['job', 'status'], name='main_placem_job_id_87b240_idx'),
        ),
        migrations.AddIndex(
            model_name='clientperformance',
            index=models.Index(fields=['client'], name='main_client_client__5b9e09_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='main_auditl_user_id_5c7864_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='main_auditl_action_17a227_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', '-timestamp'], name='main_auditl_resourc_72b68c_idx'),
        ),
    ]
