# Generated by Django 4.2.28 on 2026-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_add_client_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/%Y/%m/'),
        ),
    ]
